baseurl: /
languageCode: en-us
title: room
theme: hugo-ivy
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  posts: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "tags"
      url: "/tags/"
      weight: 1
    - name: "subscribe"
      url: "/index.xml"

params:
  description: ""
  footer: ""
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"
  rss:
    includeContent: true
    fullTextFeed: true

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS

mediaTypes:
  "application/rss+xml":
    suffixes:
      - xml
outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "index"
    isPlainText: false
    notAlternative: true
